"""Fork extension: keep the fork summary at the top of README.md current.

The block between the markers is generated from the tools tagged ``ext`` and
the fixed list of behaviour changes below, so a new fork tool shows up without
anyone editing prose. ``--check`` exits 1 when the block is stale (used by
tests/test_ext_tools.py); without it the block is rewritten in place.
"""

from __future__ import annotations

import asyncio
import sys
from pathlib import Path

from fastmcp import FastMCP

from linkedin_mcp_server.tools.ext import register_ext_tools
from linkedin_mcp_server.tools.ext_company_post import (
    register_ext_company_post_tools,
)
from linkedin_mcp_server.tools.ext_composer_probe import (
    register_ext_composer_probe_tools,
)

README = Path(__file__).resolve().parent.parent / "README.md"
BEGIN = "<!-- FORK-EXT:BEGIN (generated by scripts/fork_readme.py, do not edit) -->"
END = "<!-- FORK-EXT:END -->"

# Changes to upstream behaviour that are not a tool of their own.
BEHAVIOUR_CHANGES = [
    "`send_message` text is stricter than upstream: besides tab and other "
    "control characters, CR (also as CRLF) and invisible or bidi control "
    "characters are refused; multi-line text uses upstream's paragraph path.",
    "Profile URLs are normalised in one place (`linkedin/ext_urls.py`): "
    "benign query keys by allowlist (`isSelfProfile=false`, `trk`, ...), no "
    "fragment, percent-decoded slug (umlauts), optional locale segment; the "
    "recipient stays pinned by its profile URN and anything else fails closed.",
    "`connect_with_person` reads the 2026 More menu: `pending` when the "
    "invitation is only shown there, Connect from the menu (`connect_via: "
    "more_menu`), and a distinct `follow_only` next to `connect_unavailable`.",
    "`create_post` keeps refusing `as_company` and points at "
    "`create_company_post`, which opens the composer from the page's own "
    "admin view (`/company/<id>/admin/page-posts/published/`). That makes the "
    "page the author by construction, so the fork verifies an author instead "
    "of switching one -- the member composer at `/feed/?shareActive=true` "
    "carries no author control at all (measured 2026-10-09).",
    "A dialog is identified by what it contains, never by its position: the "
    "composer is the dialog holding an editor *and* a commit button, the "
    "schedule dialog the one holding a date field. LinkedIn's messaging "
    "overlay is a `role=\"dialog\"` with its own `role=\"textbox\"`, so "
    "\"first\" and \"last\" both pick the wrong window.",
    "Scheduling picks the time from the quarter-hour list rather than typing "
    "it: the combobox reads a written value back and discards it on confirm "
    "(a 15:00 request became 14:45). A minute off the 15-minute grid is "
    "refused up front, and the composer must show the time back.",
    "Every fork tool answers a refusal or outcome with a `status` and names "
    "its statuses in its own description. Shared by all of them: "
    "`pace_budget_spent` (pacer budget spent; wait, see `pace_status`), "
    "`pace_lock_busy` (pacer lock held; nothing booked, retry shortly) and "
    "`ledger_corrupt` (the outreach ledger has an unreadable row; repair it, "
    "nothing was sent or booked). For write tools `unknown` and `unverified` "
    "mean the action may have happened: never retry, check the thread or "
    "post by hand. `tests/test_ext_r6_doku.py` keeps descriptions and code "
    "in step.",
]


# Configuration the fork reads from the environment. Deployment identity
# (canary profile, booking account) is configured, never built in.
CONFIGURATION = [
    ("LINKEDIN_MCP_CANARY", "unset",
     "Profile slug of an own or colleague account that receives every campaign "
     "text first (`send_campaign_batch`) and that `outreach_selftest` loads. "
     "Unset: campaigns and the self-test refuse (`canary_not_configured`)."),
    ("LINKEDIN_MCP_CALENDLY_ACCOUNT", "unset",
     "The only Calendly account a message may link to (`acme_jane-doe` or "
     "`calendly.com/acme_jane-doe`). Unset: every Calendly link is refused."),
    ("LINKEDIN_MCP_INVITE_NOTE_MAX", "200",
     "Longest invitation note `connect_with_person` accepts (at most 300)."),
    ("LINKEDIN_MCP_ALLOW_UPSTREAM_WRITES", "unset",
     "`1` also registers the unguarded upstream write tools as "
     "`send_message_unguarded` / `connect_with_person_unguarded`. Leave unset."),
    ("LINKEDIN_MCP_LEDGER", "~/.linkedin-mcp/outreach-ledger.jsonl",
     "Outreach ledger: every write attempt, its outcome and the pacer bookings."),
    ("LINKEDIN_MCP_NOTES", "~/.linkedin-mcp/contact-notes.json",
     "Local contact keywords and notes (`set_contact_note`)."),
    ("LINKEDIN_MCP_ENGAGERS_SEEN", "~/.linkedin-mcp/engagers-seen.json",
     "Which post engagers were already reported (`only_new`)."),
    ("LINKEDIN_MCP_JOB_WATCH", "~/.linkedin-mcp/job-watch.json",
     "Saved searches and companies for `job_watch`."),
]

SAFETY_MODEL = [
    "**Dry run first.** Every write tool does nothing visible without "
    "`confirm=true` / `confirm_send=true`; the dry run reports what it would do.",
    "**Ledger before the click.** An attempt is written to the ledger before the "
    "action and closed with its outcome after a read-back. The same text never "
    "goes to the same person twice, and an attempt whose outcome is unclear "
    "(`unknown`, `unverified`) blocks a retry.",
    "**Pacer.** Each action kind has a daily and a rolling 7-day budget plus a "
    "daily total of visible actions (`pace_status`); a spent budget refuses "
    "before anything is loaded.",
    "**Read-back.** Messages, posts, comments, invitations and reposts are read "
    "back from the page; only a confirmed read-back counts as `verified`.",
    "**Unguarded upstream writes are hidden.** The fork's guarded tools take "
    "the upstream names `send_message` and `connect_with_person` (dry run "
    "unless `confirm_send=true`); the unguarded upstream originals are not "
    "registered. `LINKEDIN_MCP_ALLOW_UPSTREAM_WRITES=1` exposes them as "
    "`send_message_unguarded` / `connect_with_person_unguarded`, for upstream "
    "debugging only.",
]

FORK_SOURCE = "git+https://github.com/ShredFred/linkedin-mcp-server@main"

# The fork shares its package name with upstream: a bare
# `uvx mcp-server-linkedin` resolves to PyPI, i.e. upstream without the fork.
INSTALL = [
    "> **Install this fork** -- always from the Git URL. The package name is the "
    "same as upstream's, so `uvx mcp-server-linkedin` (or `@latest`) installs "
    "upstream from PyPI *without* the fork tools.",
    ">",
    "> ```bash",
    "> # run without installing (add --refresh to pick up a newer main)",
    f"> uvx --from {FORK_SOURCE} mcp-server-linkedin",
    ">",
    "> # or install as a tool, and upgrade later",
    f'> uv tool install "mcp-server-linkedin @ {FORK_SOURCE}"',
    "> uv tool upgrade mcp-server-linkedin",
    ">",
    "> # sign in once (or rely on the auto-import from a signed-in browser)",
    f"> uvx --from {FORK_SOURCE} mcp-server-linkedin --login",
    ">",
    "> # register in Claude Code with the two deployment values",
    "> claude mcp add linkedin \\",
    ">   -e UV_HTTP_TIMEOUT=300 \\",
    ">   -e LINKEDIN_MCP_CANARY=<your-test-profile-slug> \\",
    ">   -e LINKEDIN_MCP_CALENDLY_ACCOUNT=<your-calendly-account> \\",
    f">   -- uvx --from {FORK_SOURCE} mcp-server-linkedin",
    "> ```",
    ">",
    "> The upstream sections further down write `uvx mcp-server-linkedin@latest`; "
    f"for this fork read that as `uvx --from {FORK_SOURCE} mcp-server-linkedin` "
    "(options such as `--login` or `--logout` stay the same). "
    "Pin a release by replacing `@main` with a commit SHA. "
    "`outreach_selftest` checks the setup without sending anything. Without "
    "`LINKEDIN_MCP_CANARY`, campaign sends and the self-test refuse; without "
    "`LINKEDIN_MCP_CALENDLY_ACCOUNT`, every Calendly link is refused -- see "
    "*Configuration* below.",
]

# Abbreviations whose dot does not end a sentence.
_ABBREVIATIONS = ("e.g.", "i.e.", "etc.", "vs.", "z. B.", "approx.")


def _first_line(doc: str | None) -> str:
    """First sentence of the docstring's first paragraph."""
    paragraph = " ".join((doc or "").strip().split("\n\n", 1)[0].split())
    start = 0
    while True:
        at = paragraph.find(". ", start)
        if at < 0:
            return paragraph
        head = paragraph[: at + 1]
        if head.endswith(_ABBREVIATIONS):
            start = at + 2
            continue
        return head


# Add a new fork registration here, or its tools stay out of the README.
REGISTRATIONS = (
    register_ext_tools,
    register_ext_company_post_tools,
    register_ext_composer_probe_tools,
)


def render() -> str:
    mcp = FastMCP("readme")
    # Every fork registration, not just the first one: a tool the generator
    # does not register is a tool --check cannot notice is missing.
    for register in REGISTRATIONS:
        register(mcp)
    tools = sorted(asyncio.run(mcp.list_tools()), key=lambda t: t.name)
    lines = [
        BEGIN,
        "",
        "> **Hardened fork** of [stickerdaniel/linkedin-mcp-server]"
        "(https://github.com/stickerdaniel/linkedin-mcp-server). Upstream is merged in "
        "weekly; everything below is added on top of the base version and kept.",
        ">",
        *INSTALL,
        ">",
        "> **Added tools**",
        ">",
    ]
    for tool in tools:
        lines.append(f"> - `{tool.name}` — {_first_line(tool.description)}")
    lines += [">", "> **Changed behaviour**", ">"]
    lines += [f"> - {change}" for change in BEHAVIOUR_CHANGES]
    lines += [">", "> **Safety model**", ">"]
    lines += [f"> - {rule}" for rule in SAFETY_MODEL]
    lines += [
        ">",
        "> **Configuration** (environment of the MCP server process)",
        ">",
        "> | Variable | Default | Meaning |",
        "> | --- | --- | --- |",
    ]
    lines += [f"> | `{name}` | {default} | {text} |" for name, default, text in CONFIGURATION]
    lines += [
        ">",
        "> A state file from before the rename to these plain names "
        "(`<prefix>-outreach-ledger.jsonl` and so on) is used in place while "
        "the plain one is missing, so an upgrade never starts with an empty "
        "ledger; two such files are an error.",
        ">",
        "",
        END,
    ]
    return "\n".join(lines)


def updated(text: str) -> str:
    block = render()
    if BEGIN in text and END in text:
        head, rest = text.split(BEGIN, 1)
        _, tail = rest.split(END, 1)
        return head + block + tail
    # First run: after the title and the mcp-name marker upstream keeps on line 3.
    lines = text.split("\n")
    at = 3 if len(lines) > 3 and lines[2].startswith("<!-- mcp-name") else 1
    return "\n".join(lines[:at] + ["", block] + lines[at:])


def main() -> int:
    text = README.read_text(encoding="utf-8")
    new = updated(text)
    if "--check" in sys.argv:
        if new != text:
            sys.stderr.write(
                "README fork block is stale; run scripts/fork_readme.py\n"
            )
            return 1
        return 0
    if new != text:
        README.write_bytes(new.encode("utf-8"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
