"""Fork extension: keep the fork summary at the top of README.md current.

The block between the markers is generated from the tools tagged ``ext`` and
the fixed list of behaviour changes below, so a new fork tool shows up without
anyone editing prose. ``--check`` exits 1 when the block is stale (used by
tests/test_ext_tools.py); without it the block is rewritten in place.
"""

from __future__ import annotations

import asyncio
import sys
from pathlib import Path

from fastmcp import FastMCP

from linkedin_mcp_server.tools.ext import register_ext_tools

README = Path(__file__).resolve().parent.parent / "README.md"
BEGIN = "<!-- FORK-EXT:BEGIN (generated by scripts/fork_readme.py, do not edit) -->"
END = "<!-- FORK-EXT:END -->"

# Changes to upstream behaviour that are not a tool of their own.
BEHAVIOUR_CHANGES = [
    "`send_message` accepts multi-line text: LF becomes a paragraph via "
    "`insertParagraph`, never an Enter key, so no half message can be sent. "
    "CR, tab and other control characters are still refused.",
    "Profile URLs are normalised in one place (`linkedin/ext_urls.py`): "
    "benign query keys by allowlist (`isSelfProfile=false`, `trk`, ...), no "
    "fragment, percent-decoded slug (umlauts), optional locale segment; the "
    "recipient stays pinned by its profile URN and anything else fails closed.",
    "`connect_with_person` reads the 2026 More menu: `pending` when the "
    "invitation is only shown there, Connect from the menu (`connect_via: "
    "more_menu`), and a distinct `follow_only` next to `connect_unavailable`.",
    "Every fork tool answers a refusal or outcome with a `status` and names "
    "its statuses in its own description. Shared by all of them: "
    "`pace_budget_spent` (pacer budget spent; wait, see `pace_status`), "
    "`pace_lock_busy` (pacer lock held; nothing booked, retry shortly) and "
    "`ledger_corrupt` (the outreach ledger has an unreadable row; repair it, "
    "nothing was sent or booked). For write tools `unknown` and `unverified` "
    "mean the action may have happened: never retry, check the thread or "
    "post by hand. `tests/test_ext_r6_doku.py` keeps descriptions and code "
    "in step.",
]


# Configuration the fork reads from the environment. Deployment identity
# (canary profile, booking account) is configured, never built in.
CONFIGURATION = [
    ("LINKEDIN_MCP_CANARY", "unset",
     "Profile slug of an own or colleague account that receives every campaign "
     "text first (`send_campaign_batch`) and that `outreach_selftest` loads. "
     "Unset: campaigns and the self-test refuse (`canary_not_configured`)."),
    ("LINKEDIN_MCP_CALENDLY_ACCOUNT", "unset",
     "The only Calendly account a message may link to (`acme_jane-doe` or "
     "`calendly.com/acme_jane-doe`). Unset: every Calendly link is refused."),
    ("LINKEDIN_MCP_INVITE_NOTE_MAX", "200",
     "Longest invitation note `connect_guarded` accepts (at most 300)."),
    ("LINKEDIN_MCP_ALLOW_UPSTREAM_WRITES", "unset",
     "`1` lifts the block on the unguarded upstream write tools. Leave unset."),
    ("LINKEDIN_MCP_LEDGER", "~/.linkedin-mcp/outreach-ledger.jsonl",
     "Outreach ledger: every write attempt, its outcome and the pacer bookings."),
    ("LINKEDIN_MCP_NOTES", "~/.linkedin-mcp/contact-notes.json",
     "Local contact keywords and notes (`set_contact_note`)."),
    ("LINKEDIN_MCP_ENGAGERS_SEEN", "~/.linkedin-mcp/engagers-seen.json",
     "Which post engagers were already reported (`only_new`)."),
    ("LINKEDIN_MCP_JOB_WATCH", "~/.linkedin-mcp/job-watch.json",
     "Saved searches and companies for `job_watch`."),
]

SAFETY_MODEL = [
    "**Dry run first.** Every write tool does nothing visible without "
    "`confirm=true` / `confirm_send=true`; the dry run reports what it would do.",
    "**Ledger before the click.** An attempt is written to the ledger before the "
    "action and closed with its outcome after a read-back. The same text never "
    "goes to the same person twice, and an attempt whose outcome is unclear "
    "(`unknown`, `unverified`) blocks a retry.",
    "**Pacer.** Each action kind has a daily and a rolling 7-day budget plus a "
    "daily total of visible actions (`pace_status`); a spent budget refuses "
    "before anything is loaded.",
    "**Read-back.** Messages, posts, comments, invitations and reposts are read "
    "back from the page; only a confirmed read-back counts as `verified`.",
    "**Unguarded upstream writes are blocked.** `send_message` and "
    "`connect_with_person` are refused in favour of `send_message_verified` "
    "and `connect_guarded` (see `LINKEDIN_MCP_ALLOW_UPSTREAM_WRITES`).",
]

FORK_SOURCE = "git+https://github.com/ShredFred/linkedin-mcp-server@main"

# The fork shares its package name with upstream: a bare
# `uvx mcp-server-linkedin` resolves to PyPI, i.e. upstream without the fork.
INSTALL = [
    "> **Install this fork** -- always from the Git URL. The package name is the "
    "same as upstream's, so `uvx mcp-server-linkedin` (or `@latest`) installs "
    "upstream from PyPI *without* the fork tools.",
    ">",
    "> ```bash",
    "> # run without installing (add --refresh to pick up a newer main)",
    f"> uvx --from {FORK_SOURCE} mcp-server-linkedin",
    ">",
    "> # or install as a tool, and upgrade later",
    f'> uv tool install "mcp-server-linkedin @ {FORK_SOURCE}"',
    "> uv tool upgrade mcp-server-linkedin",
    ">",
    "> # sign in once (or rely on the auto-import from a signed-in browser)",
    f"> uvx --from {FORK_SOURCE} mcp-server-linkedin --login",
    ">",
    "> # register in Claude Code with the two deployment values",
    "> claude mcp add linkedin \\",
    ">   -e UV_HTTP_TIMEOUT=300 \\",
    ">   -e LINKEDIN_MCP_CANARY=<your-test-profile-slug> \\",
    ">   -e LINKEDIN_MCP_CALENDLY_ACCOUNT=<your-calendly-account> \\",
    f">   -- uvx --from {FORK_SOURCE} mcp-server-linkedin",
    "> ```",
    ">",
    "> The upstream sections further down write `uvx mcp-server-linkedin@latest`; "
    f"for this fork read that as `uvx --from {FORK_SOURCE} mcp-server-linkedin` "
    "(options such as `--login` or `--logout` stay the same). "
    "Pin a release by replacing `@main` with a commit SHA. "
    "`outreach_selftest` checks the setup without sending anything. Without "
    "`LINKEDIN_MCP_CANARY`, campaign sends and the self-test refuse; without "
    "`LINKEDIN_MCP_CALENDLY_ACCOUNT`, every Calendly link is refused -- see "
    "*Configuration* below.",
]

# Abbreviations whose dot does not end a sentence.
_ABBREVIATIONS = ("e.g.", "i.e.", "etc.", "vs.", "z. B.", "approx.")


def _first_line(doc: str | None) -> str:
    """First sentence of the docstring's first paragraph."""
    paragraph = " ".join((doc or "").strip().split("\n\n", 1)[0].split())
    start = 0
    while True:
        at = paragraph.find(". ", start)
        if at < 0:
            return paragraph
        head = paragraph[: at + 1]
        if head.endswith(_ABBREVIATIONS):
            start = at + 2
            continue
        return head


def render() -> str:
    mcp = FastMCP("readme")
    register_ext_tools(mcp)
    tools = sorted(asyncio.run(mcp.list_tools()), key=lambda t: t.name)
    lines = [
        BEGIN,
        "",
        "> **Hardened fork** of [stickerdaniel/linkedin-mcp-server]"
        "(https://github.com/stickerdaniel/linkedin-mcp-server). Upstream is merged in "
        "weekly; everything below is added on top of the base version and kept.",
        ">",
        *INSTALL,
        ">",
        "> **Added tools**",
        ">",
    ]
    for tool in tools:
        lines.append(f"> - `{tool.name}` — {_first_line(tool.description)}")
    lines += [">", "> **Changed behaviour**", ">"]
    lines += [f"> - {change}" for change in BEHAVIOUR_CHANGES]
    lines += [">", "> **Safety model**", ">"]
    lines += [f"> - {rule}" for rule in SAFETY_MODEL]
    lines += [
        ">",
        "> **Configuration** (environment of the MCP server process)",
        ">",
        "> | Variable | Default | Meaning |",
        "> | --- | --- | --- |",
    ]
    lines += [f"> | `{name}` | {default} | {text} |" for name, default, text in CONFIGURATION]
    lines += [
        ">",
        "> A state file from before the rename to these plain names "
        "(`<prefix>-outreach-ledger.jsonl` and so on) is used in place while "
        "the plain one is missing, so an upgrade never starts with an empty "
        "ledger; two such files are an error.",
        ">",
        "",
        END,
    ]
    return "\n".join(lines)


def updated(text: str) -> str:
    block = render()
    if BEGIN in text and END in text:
        head, rest = text.split(BEGIN, 1)
        _, tail = rest.split(END, 1)
        return head + block + tail
    # First run: after the title and the mcp-name marker upstream keeps on line 3.
    lines = text.split("\n")
    at = 3 if len(lines) > 3 and lines[2].startswith("<!-- mcp-name") else 1
    return "\n".join(lines[:at] + ["", block] + lines[at:])


def main() -> int:
    text = README.read_text(encoding="utf-8")
    new = updated(text)
    if "--check" in sys.argv:
        if new != text:
            sys.stderr.write(
                "README fork block is stale; run scripts/fork_readme.py\n"
            )
            return 1
        return 0
    if new != text:
        README.write_bytes(new.encode("utf-8"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
