"""MiViA fork: keep the fork summary at the top of README.md current.

The block between the markers is generated from the tools tagged ``mivia`` and
the fixed list of behaviour changes below, so a new fork tool shows up without
anyone editing prose. ``--check`` exits 1 when the block is stale (used by
tests/test_mivia_tools.py); without it the block is rewritten in place.
"""

from __future__ import annotations

import asyncio
import sys
from pathlib import Path

from fastmcp import FastMCP

from linkedin_mcp_server.tools.mivia import register_mivia_tools

README = Path(__file__).resolve().parent.parent / "README.md"
BEGIN = "<!-- MIVIA-FORK:BEGIN (generated by scripts/mivia_readme.py, do not edit) -->"
END = "<!-- MIVIA-FORK:END -->"

# Changes to upstream behaviour that are not a tool of their own.
BEHAVIOUR_CHANGES = [
    "`send_message` accepts multi-line text: LF becomes a paragraph via "
    "`insertParagraph`, never an Enter key, so no half message can be sent. "
    "CR, tab and other control characters are still refused.",
]


def _first_line(doc: str | None) -> str:
    """First sentence of the docstring's first paragraph."""
    paragraph = " ".join((doc or "").strip().split("\n\n", 1)[0].split())
    sentence, dot, _ = paragraph.partition(". ")
    return sentence + ("." if dot else "")


def render() -> str:
    mcp = FastMCP("readme")
    register_mivia_tools(mcp)
    tools = sorted(asyncio.run(mcp.list_tools()), key=lambda t: t.name)
    lines = [
        BEGIN,
        "",
        "> **MiViA fork** of [stickerdaniel/linkedin-mcp-server]"
        "(https://github.com/stickerdaniel/linkedin-mcp-server). Upstream is merged in "
        "weekly; everything below is added on top of the base version and kept.",
        ">",
        "> **Added tools**",
        ">",
    ]
    for tool in tools:
        lines.append(f"> - `{tool.name}` — {_first_line(tool.description)}")
    lines += [">", "> **Changed behaviour**", ">"]
    lines += [f"> - {change}" for change in BEHAVIOUR_CHANGES]
    lines += [
        ">",
        "> Install from this fork, not PyPI: "
        '`uv tool install "mcp-server-linkedin @ git+https://github.com/ShredFred/linkedin-mcp-server@main"`.',
        "",
        END,
    ]
    return "\n".join(lines)


def updated(text: str) -> str:
    block = render()
    if BEGIN in text and END in text:
        head, rest = text.split(BEGIN, 1)
        _, tail = rest.split(END, 1)
        return head + block + tail
    # First run: after the title and the mcp-name marker upstream keeps on line 3.
    lines = text.split("\n")
    at = 3 if len(lines) > 3 and lines[2].startswith("<!-- mcp-name") else 1
    return "\n".join(lines[:at] + ["", block] + lines[at:])


def main() -> int:
    text = README.read_text(encoding="utf-8")
    new = updated(text)
    if "--check" in sys.argv:
        if new != text:
            sys.stderr.write(
                "README fork block is stale; run scripts/mivia_readme.py\n"
            )
            return 1
        return 0
    if new != text:
        README.write_bytes(new.encode("utf-8"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
